### ISSUE TITLE
Make it possible for users to invite friends.

### ISSUE THREAD

**Issue by andela-onnenanya** [devclubaf/devclub-af-website#4]
Hi Team,

I suggest it's possible for a user of this app to be able to invite friends who might not know about the app. This way, the network grows faster.

I can work on this and raise the PR if given the opportunity.

**Comment by devclubaf** [comment]
Most welcome @andela-onnenanya 
That is great idea, you can work on that.

**Comment by andela-onnenanya** [comment]
Ok, thank you! I will do that.
